### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by zzul** [Al-Ghozy03/komikcast-api#1]
![2023-08-14-002737_1366x687_scrot](https://github.com/Al-Ghozy03/komikcast-api/assets/40860881/c8825b1a-6383-4132-9726-b303104dae79)
Error bang pas dibuka

**Comment by Al-Ghozy03** [comment]
Halo bang. Kalo yang di vercel emang bermasalah, lagi dicoba dibenerin dulu. Kalo mau akses, bisa pake yang https://komikcast-api.cyclic.app

**Comment by zzul** [comment]
Ok, thx bang
